# database Setting
spring:
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

cloud:
  aws:
    buket: ${S3_BUKET_NAME}
    stack:
      auto: false
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}

jwt:
  prefix: ${JWT_PREFIX}
  header: ${JWT_HEADER}
  secret: ${JWT_SECRET}
  access_time: ${JWT_ACCESS_TIME}
  refresh-time: ${JWT_REFRESH_TIME}