# database Setting
spring:
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

# AWS S3 Bucket
cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET_NAME}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}

jwt:
  prefix: ${JWT_PREFIX}
  header: ${JWT_HEADER}
  secret: ${JWT_SECRET}
  access_time: ${JWT_ACCESS_TIME}
  refresh-time: ${JWT_REFRESH_TIME}